print("---------------------------------------------")
child_meal_price = float(input("Price of child's meal price: $"))
adult_meal_price = float(input("Price of adults's meal price: $"))
number_of_children = int(input("Number of children: "))
number_of_adults = int(input("Number of adults: "))
drink_input = input("Do you want to add a drink? ($2 each)(Write yes/no)?: ")
if drink_input.capitalize() == "Yes":
    drink_number = int(input("How many drinks do you want to include?: "))
    drink_cost = 2
    drink_calculation = drink_number * drink_cost
    sales_tax_rate = float(input("What is the sales tax rate: "))
    print("")
    subtotal = ((number_of_children * child_meal_price) +
                (number_of_adults * adult_meal_price) + (drink_calculation))
    print(f"The subtotal is: ${subtotal}")
    sales_tax = round(((subtotal * sales_tax_rate)/100), 2)
    print(f"Sales tax is: {sales_tax}")
    total = round((subtotal + sales_tax), 2)
    print(f"Total: ${total}")
    print("")
    payment_amount = float(input("What is the payment amount: $"))
    change = round((payment_amount - total), 2)
    print(f"Change: ${change}")
else:
    sales_tax_rate = float(input("What is the sales tax rate: "))
    print("")
    # OPERATION meal's subtotal ((# children)*( price meal) + (# adults)*( price meal))
    # PRINT display the subtotal
    subtotal = ((number_of_children * child_meal_price) +
                (number_of_adults * adult_meal_price))
    print(f"The subtotal is: ${subtotal}")
    # OPERATION and PRINT sales tax ((subtotal*sales tax rate)/100)
    sales_tax = round(((subtotal * sales_tax_rate)/100), 2)
    print(f"Sales tax is: {sales_tax}")
    # OPERATION and PRINT total (subtotal + sales tax)
    total = round((subtotal + sales_tax), 2)
    print(f"Total: ${total}")
    print("")
    # INPUT payment amount (float)
    payment_amount = float(input("What is the payment amount: $"))
    # OPERATION and PRINT change (payment amount - total)
    change = round((payment_amount - total), 2)
    print(f"Change: ${change}")
