# INPUT price child's meal (float)
child_meal_price = float(input("Price of child's meal price: $"))
# INPUT price adult's meal (float)
adult_meal_price = float(input("Price of adults's meal price: $"))
# INPUT # of children (integer)
number_of_children = int(input("Number of children: "))
# INPUT #of adults (integer)
number_of_adults = int(input("Number of adults: "))
# INPUT sales tax rate (float)
sales_tax_rate = float(input("What is the sales tax rate: "))
print("")
# OPERATION meal's subtotal ((# children)*( price meal) + (# adults)*( price meal))
# PRINT display the subtotal
subtotal = ((number_of_children * child_meal_price) +
            (number_of_adults * adult_meal_price))
print(f"The subtotal is: {subtotal}")
# OPERATION and PRINT sales tax ((subtotal*sales tax rate)/100)
sales_tax = round(((subtotal * sales_tax_rate)/100), 2)
print(f"Sales tax is: {sales_tax}")
# OPERATION and PRINT total (subtotal + sales tax)
total = round((subtotal + sales_tax), 2)
print(f"Total: ${total}")
print("")
# INPUT payment amount (float)
payment_amount = float(input("What is the payment amount: $"))
# OPERATION and PRINT change (payment amount - total)
change = round((payment_amount - total), 2)
print(f"Change: ${change}")
